class_name VoiceList
# This file is auto-generated by generate_voice_list.gd. Do not edit manually.

static var beeps_paths: Array[String] = [
	"res://assets/audio/beeps/phaserUp2.mp3",
	"res://assets/audio/beeps/phaseJump3.mp3",
	"res://assets/audio/beeps/phaseJump1.mp3",
	"res://assets/audio/beeps/pepSound1.mp3",
	"res://assets/audio/beeps/phaserUp3.mp3",
	"res://assets/audio/beeps/phaserDown2.mp3",
	"res://assets/audio/beeps/phaserUp7.mp3",
	"res://assets/audio/beeps/phaseJump4.mp3",
	"res://assets/audio/beeps/phaserDown1.mp3",
	"res://assets/audio/beeps/phaserUp4.mp3",
	"res://assets/audio/beeps/phaseJump2.mp3",
	"res://assets/audio/beeps/pepSound5.mp3",
	"res://assets/audio/beeps/phaseJump5.mp3",
	"res://assets/audio/beeps/phaserUp1.mp3",
	"res://assets/audio/beeps/pepSound2.mp3",
	"res://assets/audio/beeps/phaserUp6.mp3",
	"res://assets/audio/beeps/pepSound3.mp3",
	"res://assets/audio/beeps/phaserDown3.mp3",
	"res://assets/audio/beeps/phaserUp5.mp3",
	"res://assets/audio/beeps/pepSound4.mp3"
]
