@tool
extends EditorScript

const OUTPUT_PATH = "res://modules/voice-manager/VoiceList.gd"
const BEEP_SOUNDS_FOLDER = "res://assets/audio/beeps/"

func _run():
	print("Generating voice list...")
	var script_content = "class_name VoiceList\n"
	script_content += "# This file is auto-generated by generate_voice_list.gd. Do not edit manually.\n\n"

	var files = _get_files_in_dir(BEEP_SOUNDS_FOLDER)

	var array_string = "[\n"
	for i in range(files.size()):
		array_string += "\t\"" + files[i] + "\""
		if i < files.size() - 1:
			array_string += ",\n"
		else:
			array_string += "\n"
	array_string += "]"

	script_content += "static var beeps_paths: Array[String] = %s\n" % [array_string]

	var file = FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file:
		file.store_string(script_content)
		file.close()
		print("Successfully generated VoiceList.gd")
	else:
		printerr("Failed to write to %s" % OUTPUT_PATH)

func _get_files_in_dir(path: String) -> Array[String]:
	var files: Array[String] = []
	var dir = DirAccess.open(path)
	if dir:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while file_name != "":
			if not dir.current_is_dir() and (file_name.ends_with(".mp3") or file_name.ends_with(".ogg")):
				files.append(path.path_join(file_name))
			file_name = dir.get_next()
	return files
