@tool
extends EditorScript

const OUTPUT_PATH = "res://modules/resource-manager/ResourceList.gd"

const RESOURCE_FOLDERS = {
	"bases": "res://resources/bases/",
	"effects": "res://resources/effects/",
	"encounters": "res://resources/encounters/",
	"ingredients": "res://resources/ingredients/",
	"npcs": "res://resources/npcs/",
	"products": "res://resources/products/"
}

func _run():
	print("Generating resource list...")
	var script_content = "class_name ResourceList\n"
	script_content += "# This file is auto-generated by generate_resource_list.gd. Do not edit manually.\n\n"

	for type_name in RESOURCE_FOLDERS:
		var path = RESOURCE_FOLDERS[type_name]
		var files = _get_files_in_dir(path)

		# Manually build the array string for correct syntax
		var array_string = "[\n"
		for i in range(files.size()):
			array_string += "\t\"" + files[i] + "\""
			if i < files.size() - 1:
				array_string += ",\n"
			else:
				array_string += "\n"
		array_string += "]"

		script_content += "static var %s_paths: Array[String] = %s\n" % [type_name, array_string]

	var file = FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file:
		file.store_string(script_content)
		file.close()
		print("Successfully generated ResourceList.gd")
	else:
		printerr("Failed to write to %s" % OUTPUT_PATH)

func _get_files_in_dir(path: String) -> Array[String]:
	var files: Array[String] = []
	var dir = DirAccess.open(path)
	if dir:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while file_name != "":
			if not dir.current_is_dir() and file_name.ends_with(".tres"):
				files.append(path.path_join(file_name))
			file_name = dir.get_next()
	return files
