name: GH Page Deploy

# only on master push
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # set up node version
      - name: Read .nvmrc
        run: NVMRC=$(cat ./blog/.nvmrc)

      - name: Use Node.js (.nvmrc)
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ./blog
        run: npm install

      - name: Build the site
        working-directory: ./blog
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public